-- Fixed Oracle Stored Procedures for Transaction Sync
-- Run these in your Oracle database

-- ============================================
-- INSERT PROCEDURE (FIXED - removed transaction_id)
-- ============================================
CREATE OR REPLACE PROCEDURE insert_transaction_from_sqlite (
    p_user_id          IN NUMBER,
    p_category_id      IN NUMBER,
    p_amount           IN NUMBER,
    p_transaction_type IN VARCHAR2,
    p_transaction_date IN DATE,
    p_description      IN VARCHAR2,
    p_payment_method   IN VARCHAR2,
    p_created_at       IN TIMESTAMP
)
AS
BEGIN
    INSERT INTO Transactions (
        -- transaction_id is removed - it's GENERATED ALWAYS AS IDENTITY
        user_id,
        category_id,
        amount,
        transaction_type,
        transaction_date,
        description,
        payment_method,
        created_at,
        updated_at
    ) VALUES (
        p_user_id,
        p_category_id,
        p_amount,
        p_transaction_type,
        p_transaction_date,
        p_description,
        p_payment_method,
        p_created_at,
        SYSTIMESTAMP
    );
    -- transaction_id will be auto-generated by Oracle
END insert_transaction_from_sqlite;
/

-- ============================================
-- UPDATE PROCEDURE (unchanged)
-- ============================================
CREATE OR REPLACE PROCEDURE update_transaction_from_sqlite (
    p_transaction_id   IN NUMBER,
    p_user_id          IN NUMBER,
    p_category_id      IN NUMBER,
    p_amount           IN NUMBER,
    p_transaction_type IN VARCHAR2,
    p_transaction_date IN DATE,
    p_description      IN VARCHAR2,
    p_payment_method   IN VARCHAR2
)
AS
BEGIN
    UPDATE Transactions
    SET user_id          = p_user_id,
        category_id      = p_category_id,
        amount           = p_amount,
        transaction_type = p_transaction_type,
        transaction_date = p_transaction_date,
        description      = p_description,
        payment_method   = p_payment_method,
        updated_at       = SYSTIMESTAMP
    WHERE transaction_id = p_transaction_id;
END update_transaction_from_sqlite;
/

-- ============================================
-- DELETE PROCEDURE (FIXED - delete by matching fields)
-- ============================================
-- Note: Since Oracle and SQLite have different transaction_id values,
-- we delete by matching unique fields instead
CREATE OR REPLACE PROCEDURE delete_transaction_from_sqlite (
    p_user_id          IN NUMBER,
    p_category_id      IN NUMBER,
    p_amount           IN NUMBER,
    p_transaction_type IN VARCHAR2,
    p_transaction_date IN DATE,
    p_description      IN VARCHAR2,
    p_payment_method   IN VARCHAR2
)
AS
BEGIN
    DELETE FROM Transactions
    WHERE user_id = p_user_id
      AND category_id = p_category_id
      AND amount = p_amount
      AND transaction_type = p_transaction_type
      AND transaction_date = p_transaction_date
      AND (p_description IS NULL OR description = p_description)
      AND (p_payment_method IS NULL OR payment_method = p_payment_method);
END delete_transaction_from_sqlite;
/

