
--budgets--
CREATE OR REPLACE PROCEDURE insert_budget_from_sqlite (
    p_user_id             IN NUMBER,
    p_category_id         IN NUMBER,
    p_budget_name         IN VARCHAR2,
    p_budget_description  IN VARCHAR2,
    p_budget_amount       IN NUMBER,
    p_budget_period       IN VARCHAR2,
    p_start_date          IN DATE,
    p_end_date            IN DATE,
    p_created_at          IN TIMESTAMP,
    p_updated_at          IN TIMESTAMP
) AS
BEGIN
    INSERT INTO Budgets (
        user_id, category_id, budget_name, budget_description,
        budget_amount, budget_period, start_date, end_date,
        created_at, updated_at
    ) VALUES (
        p_user_id, p_category_id, p_budget_name, p_budget_description,
        p_budget_amount, p_budget_period, p_start_date, p_end_date,
        NVL(p_created_at, SYSTIMESTAMP),
        NVL(p_updated_at, SYSTIMESTAMP)
    );
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/


CREATE OR REPLACE PROCEDURE update_budget_from_sqlite (
    p_budget_id           IN NUMBER,
    p_user_id             IN NUMBER,
    p_category_id         IN NUMBER,
    p_budget_name         IN VARCHAR2,
    p_budget_description  IN VARCHAR2,
    p_budget_amount       IN NUMBER,
    p_budget_period       IN VARCHAR2,
    p_start_date          IN DATE,
    p_end_date            IN DATE,
    p_updated_at          IN TIMESTAMP
) AS
BEGIN
    UPDATE Budgets
    SET
        user_id = p_user_id,
        category_id = p_category_id,
        budget_name = p_budget_name,
        budget_description = p_budget_description,
        budget_amount = p_budget_amount,
        budget_period = p_budget_period,
        start_date = p_start_date,
        end_date = p_end_date,
        updated_at = NVL(p_updated_at, SYSTIMESTAMP)
    WHERE budget_id = p_budget_id;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'No matching budget_id found in Oracle.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE delete_budget_from_sqlite (
    p_budget_id IN NUMBER
) AS
BEGIN
    DELETE FROM Budgets WHERE budget_id = p_budget_id;

    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'No matching budget_id found for deletion.');
    END IF;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/


--categories---



CREATE OR REPLACE PROCEDURE insertCategoryFromSQLite (
    p_category_name IN VARCHAR2,
    p_category_type IN VARCHAR2,
    p_description   IN VARCHAR2,
    p_created_at    IN TIMESTAMP
)
AS
BEGIN
    MERGE INTO Categories c
    USING (SELECT p_category_name AS category_name FROM dual) src
    ON (c.category_name = src.category_name)
    WHEN MATCHED THEN
        UPDATE SET 
            c.category_type = p_category_type,
            c.description = p_description
    WHEN NOT MATCHED THEN
        INSERT (category_name, category_type, description, created_at)
        VALUES (p_category_name, p_category_type, p_description, p_created_at);
END;
/



CREATE OR REPLACE PROCEDURE updateCategoryFromSQLite (
    p_category_id     IN NUMBER,
    p_category_name   IN VARCHAR2,
    p_category_type   IN VARCHAR2,
    p_description     IN VARCHAR2
) AS
BEGIN
    UPDATE Categories
    SET category_name = p_category_name,
        category_type = p_category_type,
        description   = p_description
    WHERE category_id = p_category_id;

    COMMIT;
END updateCategoryFromSQLite;


CREATE OR REPLACE PROCEDURE deleteCategoryFromSQLite (
    p_category_id IN NUMBER
) AS
BEGIN
    DELETE FROM Categories WHERE category_id = p_category_id;
    COMMIT;
END deleteCategoryFromSQLite;
/


---Transactions---

DROP PROCEDURE delete_transaction_from_sqlite;

CREATE OR REPLACE PROCEDURE insert_transaction_from_sqlite (
    p_user_id          IN NUMBER,
    p_category_id      IN NUMBER,
    p_amount           IN NUMBER,
    p_transaction_type IN VARCHAR2,
    p_transaction_date IN DATE,
    p_description      IN VARCHAR2,
    p_payment_method   IN VARCHAR2,
    p_created_at       IN TIMESTAMP
)
AS
BEGIN
    INSERT INTO Transactions (
        -- transaction_id is removed - it's GENERATED ALWAYS AS IDENTITY
        user_id,
        category_id,
        amount,
        transaction_type,
        transaction_date,
        description,
        payment_method,
        created_at,
        updated_at
    ) VALUES (
        p_user_id,
        p_category_id,
        p_amount,
        p_transaction_type,
        p_transaction_date,
        p_description,
        p_payment_method,
        p_created_at,
        SYSTIMESTAMP
    );
    -- transaction_id will be auto-generated by Oracle
END insert_transaction_from_sqlite;
/


CREATE OR REPLACE PROCEDURE update_transaction_from_sqlite (
    p_transaction_id   IN NUMBER,
    p_user_id          IN NUMBER,
    p_category_id      IN NUMBER,
    p_amount           IN NUMBER,
    p_transaction_type IN VARCHAR2,
    p_transaction_date IN DATE,
    p_description      IN VARCHAR2,
    p_payment_method   IN VARCHAR2
)
AS
BEGIN
    UPDATE Transactions
    SET user_id          = p_user_id,
        category_id      = p_category_id,
        amount           = p_amount,
        transaction_type = p_transaction_type,
        transaction_date = p_transaction_date,
        description      = p_description,
        payment_method   = p_payment_method,
        updated_at       = SYSTIMESTAMP
    WHERE transaction_id = p_transaction_id;
END update_transaction_from_sqlite;
/


CREATE OR REPLACE PROCEDURE delete_transaction_from_sqlite (
    p_user_id          IN NUMBER,
    p_category_id      IN NUMBER,
    p_amount           IN NUMBER,
    p_transaction_type IN VARCHAR2,
    p_transaction_date IN DATE,
    p_description      IN VARCHAR2,
    p_payment_method   IN VARCHAR2
)
AS
BEGIN
    DELETE FROM Transactions
    WHERE user_id = p_user_id
      AND category_id = p_category_id
      AND amount = p_amount
      AND transaction_type = p_transaction_type
      AND transaction_date = p_transaction_date
      AND (p_description IS NULL OR description = p_description)
      AND (p_payment_method IS NULL OR payment_method = p_payment_method);
END delete_transaction_from_sqlite;
/



--- Savings ---

-- Insert procedure
CREATE OR REPLACE PROCEDURE insertSavingFromSQLite(
    p_user_id IN NUMBER,
    p_goal_name IN VARCHAR2,
    p_target_amount IN NUMBER,
    p_current_amount IN NUMBER,
    p_target_date IN DATE,
    p_created_at IN TIMESTAMP,
    p_updated_at IN TIMESTAMP,
    p_status IN VARCHAR2
) AS
BEGIN
    INSERT INTO SavingsGoals (
        user_id, goal_name, target_amount, current_amount, target_date, created_at, updated_at, status
    ) VALUES (
        p_user_id, p_goal_name, p_target_amount, p_current_amount, p_target_date, p_created_at, p_updated_at, p_status
    );
END;
/

-- Update procedure
CREATE OR REPLACE PROCEDURE updateSavingFromSQLite(
    p_goal_id IN NUMBER,
    p_user_id IN NUMBER,
    p_goal_name IN VARCHAR2,
    p_target_amount IN NUMBER,
    p_current_amount IN NUMBER,
    p_target_date IN DATE,
    p_updated_at IN TIMESTAMP,
    p_status IN VARCHAR2
) AS
BEGIN
    UPDATE SavingsGoals
    SET user_id = p_user_id,
        goal_name = p_goal_name,
        target_amount = p_target_amount,
        current_amount = p_current_amount,
        target_date = p_target_date,
        updated_at = p_updated_at,
        status = p_status
    WHERE goal_id = p_goal_id;
END;
/

-- Delete procedure
CREATE OR REPLACE PROCEDURE deleteSavingFromSQLite(
    p_goal_id IN NUMBER
) AS
BEGIN
    DELETE FROM SavingsGoals WHERE goal_id = p_goal_id;
END;
/



----users-----
CREATE OR REPLACE PROCEDURE insertUserFromSQLite(
    p_username IN VARCHAR2,
    p_email IN VARCHAR2,
    p_password_hash IN VARCHAR2,
    p_created_at IN TIMESTAMP DEFAULT SYSTIMESTAMP,
    p_updated_at IN TIMESTAMP DEFAULT SYSTIMESTAMP
)
IS
BEGIN
    INSERT INTO Users (username, email, password_hash, created_at, updated_at)
    VALUES (p_username, p_email, p_password_hash, p_created_at, p_updated_at);
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END insertUserFromSQLite;
/




